CC=gcc

all: dealer server c1 c2 c3

dealer: dealer.c
	$(CC) dealer.c -o dealer

server: server.c
	$(CC) server.c -o server

c1: client.c
	$(CC) client.c -o c1

c2: client.c
	$(CC) client.c -o c2

c3: client.c
	$(CC) client.c -o c3